version: "3"
services:
  server:
    build: ./api
    ports:
      - "4000:4000"
  quizapp:
    build: ./quizapp
    ports:
      - "8080:8080"
    volumes:
      - './quizapp:/app'
      - '/app/node_modules'
