version: "3"
services:
  server:
    build: ./api
    ports:
      - "4000:4000"
  # quizapp:
  #   build: ./quizapp
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - './quizapp:/usr/share/nginx/html'
